---
resources:
- name: dominus
  type: git
  source:
    uri: https://github.com/openaristos/dominus.git
    branch: master
jobs:
- name: build
  plan:
  - get: dominus
    trigger: true
  - task: build
    file: dominus/ci/concourse/build-task.yml